apiVersion: v1
kind: ConfigMap
metadata:
  name: investigacion-config
data:
  application-kubernetes.yml: |
    spring:
      kafka:
        bootstrap-servers: kafka-service:9092
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics