apiVersion: apps/v1
kind: Deployment
metadata:
  name: investigacion-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: investigacion-app
  template:
    metadata:
      labels:
        app: investigacion-app
    spec:
      containers:
        - name: investigacion-app
          image: investigacion-app:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: investigacion-service
spec:
  selector:
    app: investigacion-app
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer